//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int aid { get; set; }
        public int uid { get; set; }
        public System.DateTime joining_date { get; set; }
    
        public virtual User User { get; set; }
    }
}
