//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertSolution
    {
        public int esid { get; set; }
        public int eid { get; set; }
        public int sid { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Solution Solution { get; set; }
    }
}
