//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RYCEntities : DbContext
    {
        public RYCEntities()
            : base("name=RYCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Expert> Experts { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<UserRating> UserRatings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleProblemSolution> VehicleProblemSolutions { get; set; }
        public virtual DbSet<ExpertSolution> ExpertSolutions { get; set; }
        public virtual DbSet<UserVehicle> UserVehicles { get; set; }
    }
}
