//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int stepid { get; set; }
        public int sid { get; set; }
        public int stepNo { get; set; }
        public string stepImg { get; set; }
        public string stepDescription { get; set; }
    
        public virtual Solution Solution { get; set; }
    }
}
