//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVehicle
    {
        public int id { get; set; }
        public int uid { get; set; }
        public int vid { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
