//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleProblemSolution
    {
        public int id { get; set; }
        public int eid { get; set; }
        public int vid { get; set; }
        public int sid { get; set; }
        public int pid { get; set; }
        public decimal overallrating { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual Solution Solution { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
